# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\eric\pyqt01\main_pyqt01.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1100, 860)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(460, 30, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(29)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 620, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(490, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_2 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 170, 31, 31))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_4 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_5 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.pushButton_6 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(940, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_7.setGeometry(QtCore.QRect(800, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(850, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_8 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_8.setGeometry(QtCore.QRect(660, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(710, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(570, 280, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pushButton_9 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_9.setGeometry(QtCore.QRect(500, 390, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(410, 390, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.pushButton_10 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_10.setGeometry(QtCore.QRect(640, 390, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.lineEdit_9 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(550, 390, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(400, 490, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pushButton_12 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_12.setGeometry(QtCore.QRect(650, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setText(_fromUtf8(""))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_11 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_11.setGeometry(QtCore.QRect(490, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setText(_fromUtf8(""))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.lineEdit_11 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(560, 490, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(390, 610, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.pushButton_13 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_13.setGeometry(QtCore.QRect(480, 610, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setText(_fromUtf8(""))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.lineEdit_13 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(570, 610, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.pushButton_14 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_14.setGeometry(QtCore.QRect(660, 610, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setText(_fromUtf8(""))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_15.setGeometry(QtCore.QRect(670, 720, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setText(_fromUtf8(""))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.lineEdit_14 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(580, 720, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.pushButton_16 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_16.setGeometry(QtCore.QRect(470, 720, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setText(_fromUtf8(""))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.lineEdit_15 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(380, 720, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.pushButton_17 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_17.setGeometry(QtCore.QRect(330, 720, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setText(_fromUtf8(""))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.lineEdit_16 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(240, 720, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.pushButton_18 = QtGui.QPushButton(self.centralWidget)
        self.pushButton_18.setGeometry(QtCore.QRect(810, 720, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setText(_fromUtf8(""))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.lineEdit_17 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(720, 720, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.horizontalSlider = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(490, 140, 121, 21))
        self.horizontalSlider.setMinimum(500)
        self.horizontalSlider.setMaximum(2500)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 1500)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider_2 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(110, 250, 121, 21))
        self.horizontalSlider_2.setMinimum(500)
        self.horizontalSlider_2.setMaximum(2500)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 1500)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalSlider_3 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(250, 250, 121, 21))
        self.horizontalSlider_3.setMinimum(500)
        self.horizontalSlider_3.setMaximum(2500)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setProperty("value", 1500)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.horizontalSlider_4 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(390, 250, 121, 21))
        self.horizontalSlider_4.setMinimum(500)
        self.horizontalSlider_4.setMaximum(2500)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 1500)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.horizontalSlider_5 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(850, 250, 121, 21))
        self.horizontalSlider_5.setMinimum(500)
        self.horizontalSlider_5.setMaximum(2500)
        self.horizontalSlider_5.setPageStep(1)
        self.horizontalSlider_5.setProperty("value", 1500)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.horizontalSlider_6 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(710, 250, 121, 21))
        self.horizontalSlider_6.setMinimum(500)
        self.horizontalSlider_6.setMaximum(2500)
        self.horizontalSlider_6.setPageStep(1)
        self.horizontalSlider_6.setProperty("value", 1500)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.horizontalSlider_7 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(570, 250, 121, 21))
        self.horizontalSlider_7.setMinimum(500)
        self.horizontalSlider_7.setMaximum(2500)
        self.horizontalSlider_7.setPageStep(1)
        self.horizontalSlider_7.setProperty("value", 1500)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        self.horizontalSlider_8 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_8.setGeometry(QtCore.QRect(410, 360, 121, 21))
        self.horizontalSlider_8.setMinimum(500)
        self.horizontalSlider_8.setMaximum(2500)
        self.horizontalSlider_8.setPageStep(1)
        self.horizontalSlider_8.setProperty("value", 1500)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName(_fromUtf8("horizontalSlider_8"))
        self.horizontalSlider_9 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_9.setGeometry(QtCore.QRect(550, 360, 121, 21))
        self.horizontalSlider_9.setMinimum(500)
        self.horizontalSlider_9.setMaximum(2500)
        self.horizontalSlider_9.setPageStep(1)
        self.horizontalSlider_9.setProperty("value", 1500)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName(_fromUtf8("horizontalSlider_9"))
        self.horizontalSlider_10 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_10.setGeometry(QtCore.QRect(400, 460, 121, 21))
        self.horizontalSlider_10.setMinimum(500)
        self.horizontalSlider_10.setMaximum(2500)
        self.horizontalSlider_10.setPageStep(1)
        self.horizontalSlider_10.setProperty("value", 1500)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName(_fromUtf8("horizontalSlider_10"))
        self.horizontalSlider_11 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(560, 460, 121, 21))
        self.horizontalSlider_11.setMinimum(500)
        self.horizontalSlider_11.setMaximum(2500)
        self.horizontalSlider_11.setPageStep(1)
        self.horizontalSlider_11.setProperty("value", 1500)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName(_fromUtf8("horizontalSlider_11"))
        self.horizontalSlider_12 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(390, 580, 121, 21))
        self.horizontalSlider_12.setMinimum(500)
        self.horizontalSlider_12.setMaximum(2500)
        self.horizontalSlider_12.setPageStep(1)
        self.horizontalSlider_12.setProperty("value", 1500)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName(_fromUtf8("horizontalSlider_12"))
        self.horizontalSlider_13 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(570, 580, 121, 21))
        self.horizontalSlider_13.setMinimum(500)
        self.horizontalSlider_13.setMaximum(2500)
        self.horizontalSlider_13.setPageStep(1)
        self.horizontalSlider_13.setProperty("value", 1500)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName(_fromUtf8("horizontalSlider_13"))
        self.horizontalSlider_14 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(580, 690, 121, 21))
        self.horizontalSlider_14.setMinimum(500)
        self.horizontalSlider_14.setMaximum(2500)
        self.horizontalSlider_14.setPageStep(1)
        self.horizontalSlider_14.setProperty("value", 1500)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName(_fromUtf8("horizontalSlider_14"))
        self.horizontalSlider_15 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(380, 690, 121, 21))
        self.horizontalSlider_15.setMinimum(500)
        self.horizontalSlider_15.setMaximum(2500)
        self.horizontalSlider_15.setPageStep(1)
        self.horizontalSlider_15.setProperty("value", 1500)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setObjectName(_fromUtf8("horizontalSlider_15"))
        self.horizontalSlider_16 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_16.setGeometry(QtCore.QRect(240, 690, 121, 21))
        self.horizontalSlider_16.setMinimum(500)
        self.horizontalSlider_16.setMaximum(2500)
        self.horizontalSlider_16.setPageStep(1)
        self.horizontalSlider_16.setProperty("value", 1500)
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setObjectName(_fromUtf8("horizontalSlider_16"))
        self.horizontalSlider_17 = QtGui.QSlider(self.centralWidget)
        self.horizontalSlider_17.setGeometry(QtCore.QRect(720, 690, 121, 21))
        self.horizontalSlider_17.setMinimum(500)
        self.horizontalSlider_17.setMaximum(2500)
        self.horizontalSlider_17.setPageStep(1)
        self.horizontalSlider_17.setProperty("value", 1500)
        self.horizontalSlider_17.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_17.setObjectName(_fromUtf8("horizontalSlider_17"))
        self.re = QtGui.QPushButton(self.centralWidget)
        self.re.setGeometry(QtCore.QRect(900, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.re.setFont(font)
        self.re.setObjectName(_fromUtf8("re"))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "CCNU ROB", None))
        self.pushButton.setText(_translate("MainWindow", "Add", None))
        self.lineEdit.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_2.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_3.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_4.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_5.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_6.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_7.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_8.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_9.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_10.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_11.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_12.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_13.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_14.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_15.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_16.setText(_translate("MainWindow", "1500", None))
        self.lineEdit_17.setText(_translate("MainWindow", "1500", None))
        self.re.setText(_translate("MainWindow", "restoration", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

